services:
  psql:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "jira"
      POSTGRES_USER: "jira"
      POSTGRES_PASSWORD: "JiraRush"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./src/main/resources/db/changelog:/docker-entrypoint-initdb.d

  nginx:
    image: nginx:latest
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_LIQUIBASE_CHANGELOG=classpath:db/changelog/changelog.sql
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql:5432/jira
      - SPRING_DATASOURCE_USERNAME=jira
      - SPRING_DATASOURCE_PASSWORD=JiraRush
    depends_on:
      - psql
      - nginx
    ports:
      - "8080:8080"
volumes:
  postgres-data: