services:
  db1:
    image: postgres:latest
    build:
      context: ./
    container_name: "jira_db"
    environment:
      POSTGRES_DB: "jira"
      POSTGRES_USER: "jira"
      POSTGRES_PASSWORD: "JiraRush"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./src/main/resources/data4dev:/docker-entrypoint-initdb.d
  db2:
    image: postgres:latest
    build:
      context: ./
    container_name: "jira-test_db"
    environment:
      POSTGRES_DB: "jira-test"
      POSTGRES_USER: "jira"
      POSTGRES_PASSWORD: "JiraRush"

    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/psql/data
      - ./src/main/resources/data4test:/docker-entrypoint-initdb.d

  nginx:
    image: nginx:latest
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_LIQUIBASE_CHANGELOG="classpath:db/changelog/changelog.sql"
    depends_on:
      - db1
      - db2
      - nginx
    ports:
      - "8080:8080"
volumes:
  postgres-data: